//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Church_Attendance_Goal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Church_Attendance_Goal()
        {
            this.Church_Attendance_Feedback = new HashSet<Church_Attendance_Feedback>();
        }
    
        public int ChurchAttGoalID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int Overseer { get; set; }
        public int Member { get; set; }
        public int Leader { get; set; }
        public int Visitors { get; set; }
        public int FirstTimeVisitors { get; set; }
        public int Salvations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Church_Attendance_Feedback> Church_Attendance_Feedback { get; set; }
    }
}
