//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipleship_Goal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discipleship_Goal()
        {
            this.Discipleship_Feedback = new HashSet<Discipleship_Feedback>();
        }
    
        public int DiscipleshipGoalID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string DiscipleshipType { get; set; }
        public Nullable<int> Attendance { get; set; }
        public int Overseer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipleship_Feedback> Discipleship_Feedback { get; set; }
    }
}
