//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipleship_Feedback
    {
        public int DiscipleshipFeedbackID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string DiscipleshipType { get; set; }
        public Nullable<int> Attendance { get; set; }
        public int DiscipleshipGoalID { get; set; }
        public int OrgIndivPosID { get; set; }
    
        public virtual Discipleship_Goal Discipleship_Goal { get; set; }
        public virtual Organisational_Individual_Position Organisational_Individual_Position { get; set; }
    }
}
