//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homecell_Notes
    {
        public int HCNID { get; set; }
        public string HomecellNotes { get; set; }
        public System.DateTime UploadDate { get; set; }
    }
}
