//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leader_Follow_Up
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public bool FollowUpStatus { get; set; }
        public int ZonePastor { get; set; }
        public int Overseer { get; set; }
        public int Coordinatir { get; set; }
        public int HomecellLeader { get; set; }
        public string Comment { get; set; }
        public System.DateTime FollowUpDate { get; set; }
        public Nullable<bool> NoAnswer { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
