//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members_Serve_Follow_Up
    {
        public int ServeRequestID { get; set; }
        public int PersonID { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public int ZonePastor { get; set; }
        public int Homecell { get; set; }
        public string SpiritualGiftTestSession { get; set; }
        public string HighestSpiritualGifts { get; set; }
        public int Group1 { get; set; }
        public Nullable<int> Group2 { get; set; }
        public Nullable<int> Group3 { get; set; }
        public string Comment { get; set; }
        public bool FollowUpStatus { get; set; }
        public bool NoAnswer { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
