//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NMO_Feedback
    {
        public int NMOFeedbackID { get; set; }
        public System.DateTime Date { get; set; }
        public int MonthTotal { get; set; }
        public int NMOGoalID { get; set; }
        public int OrgIndivPosID { get; set; }
    
        public virtual NMO_Goal NMO_Goal { get; set; }
        public virtual Organisational_Individual_Position Organisational_Individual_Position { get; set; }
    }
}
