//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisational_Individual_Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organisational_Individual_Position()
        {
            this.Church_Attendance_Feedback = new HashSet<Church_Attendance_Feedback>();
            this.Discipleship_Feedback = new HashSet<Discipleship_Feedback>();
            this.Homecell_Attendance_Feedback = new HashSet<Homecell_Attendance_Feedback>();
            this.NMO_Feedback = new HashSet<NMO_Feedback>();
            this.Organisational_Structure_Position = new HashSet<Organisational_Structure_Position>();
            this.Structure_Growth_Feedback = new HashSet<Structure_Growth_Feedback>();
            this.Zone_Church_Attendance_Feedback = new HashSet<Zone_Church_Attendance_Feedback>();
            this.Zone_Growth_Feedback = new HashSet<Zone_Growth_Feedback>();
            this.Zone_Homecell_Attendance_Feedback = new HashSet<Zone_Homecell_Attendance_Feedback>();
            this.Goal_Access = new HashSet<Goal_Access>();
            this.Use_Cases = new HashSet<Use_Cases>();
        }
    
        public int OrgIndivPosID { get; set; }
        public string Decription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Church_Attendance_Feedback> Church_Attendance_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipleship_Feedback> Discipleship_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Homecell_Attendance_Feedback> Homecell_Attendance_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NMO_Feedback> NMO_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organisational_Structure_Position> Organisational_Structure_Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Structure_Growth_Feedback> Structure_Growth_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zone_Church_Attendance_Feedback> Zone_Church_Attendance_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zone_Growth_Feedback> Zone_Growth_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zone_Homecell_Attendance_Feedback> Zone_Homecell_Attendance_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goal_Access> Goal_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Use_Cases> Use_Cases { get; set; }
    }
}
