//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingDiscipleship
    {
        public int personid { get; set; }
        public int discipleshipid { get; set; }
        public string discipleshipdescription { get; set; }
    }
}
