//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Children
    {
        public int KidsChurchID { get; set; }
        public int PersonID { get; set; }
        public int ChildID { get; set; }
        public Nullable<bool> KCVolunteerConfirmation { get; set; }
        public Nullable<bool> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckInDateTime { get; set; }
        public Nullable<bool> SignOut { get; set; }
        public Nullable<System.DateTime> SignOutDateTime { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual KidsChurch KidsChurch { get; set; }
        public virtual Person Person { get; set; }
    }
}
