//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salvation
    {
        public int SalID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AlterWorker { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string Age { get; set; }
        public string EmploymentStatus { get; set; }
        public string MaritualStatus { get; set; }
        public string ResidentialAddress { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string HomeTelNo { get; set; }
        public string WorkTelNo { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Invited { get; set; }
        public string NameSurnameInvite { get; set; }
        public string HomecellLeader { get; set; }
        public string ZonePastor { get; set; }
        public string StudyAddress { get; set; }
        public string SchoolLevel { get; set; }
        public string NameofSchool { get; set; }
        public string Grade { get; set; }
        public string StudyYear { get; set; }
        public string Institution { get; set; }
        public string ParentGuardianCell { get; set; }
        public string PrayerRequest { get; set; }
        public Nullable<bool> NoAnswer { get; set; }
        public Nullable<bool> FollowedUp { get; set; }
        public string Name { get; set; }
    }
}
