//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure_Growth_Goal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Structure_Growth_Goal()
        {
            this.Structure_Growth_Feedback = new HashSet<Structure_Growth_Feedback>();
        }
    
        public int StructureGrowthGoalID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public int Members { get; set; }
        public int Overseer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Structure_Growth_Feedback> Structure_Growth_Feedback { get; set; }
    }
}
